baseURL = "/"
languageCode = "en-us"
title = "SBCloud Documentation"
theme= "hugo-theme-learn"
staticDir = ["static"]
pluralizelisttitles = false
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
